### ISSUE TITLE
Label EBI retired tools as "obsolete"

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#290] opened 2017-11-22 19:26 UTC
Some tools in EBI portfolio have been retired; the corresponding bio.tools entries need retiring.  I will provide a list of tools here, once we have this their visibility flag needs setting FALSE.  cc @hansioan

**Comment by joncison** [comment] 2017-11-28 02:30
These tools have, or are in the process of being, retired.  They need to be marked as "Permanently down" (https://github.com/bio-tools/biotoolsregistry/issues/207) or - I wonder - assigned a new status value of "retired" (to indicated tools we know have been retired, rather than just being unfindable) - but maybe that is OTT? 

- Small Molecule Search (reactome) : https://bio.tools/reactome_small_molecule_search
- ChEMBL NTD Small Molecule Search : https://bio.tools/chembl_ntd_small_molecule_search
- GPCR SARfari BLAST Search : https://bio.tools/gpcr_sarfari_small_molecule_search
- GPCR SARfari Small Molecule Search : https://bio.tools/gpcr_sarfari_small_molecule_search
- Kinase SARfari BLAST Search : https://bio.tools/kinase_sarfari_blast_search
- Kinase SARfari Small Molecule Search : https://bio.tools/kinase_sarfari_small_molecule_search
- CENSOR : https://bio.tools/censor
- ClustalW2 : https://bio.tools/clustalw2_ebi
- ClustalW2 API (EBI) : https://bio.tools/clustalw2_api_ebi
- DaliLiteis : https://bio.tools/dalilite
- deCODE : https://bio.tools/decode
- MaxSprout : https://bio.tools/maxsprout
- ReadSeqis : https://bio.tools/readseq
- reLATE : https://bio.tools/relate
- FingerPRINTScan : https://bio.tools/fingerprintscan
- PROSITE Scan : https://bio.tools/prosite_scan_ebi
- CSS : https://bio.tools/css
- DASty : https://bio.tools/dasty
- MageComet : https://bio.tools/magecomet
- Phenotator : https://bio.tools/phenotator
- PITA : https://bio.tools/pita
- Advanced PDB search : https://bio.tools/advanced_pdb_search
- HMMER hmmscan : https://bio.tools/hmmscan_ebi

**Comment by hedi-ee** [comment] 2017-12-11 12:55
I think it does make sense to keep them visible (also this is mentioned in the paper draft) and retired as status suits fine (people can still find them but would know that it is not worth working with these). Maybe this could go along with suggesting a similar but active tool to the user next to retired tool entry?

**Comment by joncison** [comment] 2017-12-11 13:01
This is fine by me, but then we need a clear label on the Tool Cards.  This will be needed for sure, as high turnover of tools is inevitable, and we have to provide a persistent reference. 

For now @hansioan it is better to hide them, than show them without the label.

**Comment by hansioan** [comment] 2017-12-11 17:05
@joncison Hiding them now, just to make them visible later when the labels are set, is an extra operations which also reduces the number of tools ... Also I will have to keep track of these hidden tools and remember to get them back... I prefer to fix all when the labels are available.

**Comment by joncison** [comment] 2017-12-11 19:03
hmm ... in which case we need a label on the Tool Cards now (hardly a big job) because if a reviewer sees Tool Cards with broken homepage URLs (and they will), it will not go down well - it's one of the most basic aspects of content quality.

**Comment by joncison** [comment] 2018-09-06 11:05
cc @hedi-ee - soon there will be a way to mark-up officially obsolete tools (see also https://github.com/bio-tools/biotoolsRegistry/issues/305), and they will get labelled as such.  Initially the "obsolete" assignation will be settable by bio.tools admin only, eventually maybe by users too.

**Comment by anitamnd** [comment] 2024-09-11 11:58
Duplicate of #305

**Closed by anitamnd** 2024-09-11 11:58 UTC
Labels: content, high priority, housekeeping
