### ISSUE TITLE
Unable to view or edit a recently submitted entry

### ISSUE THREAD

**Issue by OlivierCollin** [bio-tools/biotoolsregistry#95] opened 2016-03-24 16:25 UTC
This concerns the SRD resource 
https://bio.tools/tool/irisa.fr/SRD:%20a%20Staphylococcus%20regulatory%20RNA%20database/1 

Error message : You do not have permissions to edit this resource.

**Comment by fbucchini** [comment] 2016-03-24 17:39
I'm to reproduce the issue for one of my own tools: https://bio.tools/edit/issb.genopole.fr/GREAT:SCAN:patterns/1

**Comment by OlivierCollin** [comment] 2016-03-25 07:54
It could be the ":" character in the name of the registered resource that cause this issue ?

**Comment by fbucchini** [comment] 2016-03-25 10:31
I was also suspecting something like that at first, but it seems that this problem is not specific to names containing ':' only. It seems to be a problem for all tools having special characters in their names.

For instance, I'm not able to view [this tool](https://bio.tools/tool/cns.fr/MicroScope%252FMaGe/1) (MicroScope MaGe), that has a blank space in its name. However, I'm able to view tools registered yesterday/today that have names not containing special characters (for example [this tool, pylogeny.fr](https://bio.tools/tool/pasteur.fr/Phylogeny.fr/1)).

**Comment by ekry** [comment] 2016-03-25 10:36
@OlivierCollin That is unfortunately exactly correct. Currently tool names can contain unsafe characters which leads to this behavior. We are working on a rewrite of the system where a tool will be identifiable with a single id that will only consist of URI safe characters as per section 2.3 of [RFC 3986](https://www.google.com/url?q=https://www.google.com/url?q%3Dhttp://www.ietf.org/rfc/rfc3986.txt%26amp;sa%3DD%26amp;ust%3D1458905523215000%26amp;usg%3DAFQjCNGL_HbWXbJIFy0zeHRrrx6pjM-U5w&sa=D&ust=1458905523229000&usg=AFQjCNH1BnxBpc-Jnyi6eofS2nGVDkCn0Q). This will be documented in our upcoming documentation and you will be informed of the change.

**Comment by OlivierCollin** [comment] 2016-03-29 15:17
Thank you Emil. How can we proceed ? Can you manually delete this entry so I can re-enter without the offending characters ?

**Comment by joncison** [comment] 2017-03-19 08:18
This issue has (I hope completely) been resolved by having separate tool name and (URL safe) toolID that is used in the Tool Card URLs

**Closed by joncison** 2017-03-19 08:18 UTC
Labels: API, bug
