### ISSUE TITLE
broken homepages

### ISSUE THREAD

**Issue by redmitry** [bio-tools/biotoolsRegistry#223] opened 2017-07-25 11:30 UTC
Here is the list of broken homepages.
Note that some of them may be a "false positives".
There are some weird cases (browsers are more smart than programmatic HTTP Client), but I am working on it.
Sourceforge doesn't return page if "User-Agent:" set to "Mozilla/5.0" ...
[broken3.txt](https://github.com/bio-tools/biotoolsregistry/files/1173346/broken3.txt)

**Comment by hansioan** [comment] 2017-08-08 14:04
@redmitry 
I see that some tools have the name followed by a colon ":" and then I assume it's the version. This doesn't happen for all tools so I assume the ones that don't have a name followed by a colon and something after, have the version = none. 
Am I correct in my assuptions?

**Comment by redmitry** [comment] 2017-08-08 14:12
Exactly. Tools in the list follow a {ID}[:{version}] pattern.
I think the "none" is an artifact from some internal bio.tools processing... 
although we have to live with it...

**Comment by joncison** [comment] 2017-11-22 19:57
@hansioan : pls. reassign this task to one of your guys.  We discussed the logic around how to process this at the last meeting.    Heads-up @ekry that for entries where we set the homepageURL bit to "confirmed unavailable" (or whatever) we'll need to render this information in the Tool Card.

To close this issues we'd need all URLs in @redmitry list above checked, and the "Unavailable" label (or whatever we decide) in the Tool Card.

**Comment by hansioan** [comment] 2017-11-22 22:25
@joncison 
The broken homepages have been fix, whatever could be fixed. There are many for which there is no other homepage. We did not delete the tool because we want to be persistent in the id.

**Comment by joncison** [comment] 2017-11-22 22:27
Thanks, brilliant - just got the link.  Then the last thing to do is update the database as per https://github.com/bio-tools/biotoolsregistry/issues/207 and also - to close this issue - apply an appropriate label to the Tool Card (cc @ekry )

**Comment by joncison** [comment] 2018-09-05 10:07
The problem reported in the OP is fixed, labelling the Tool Cards appropriately is a separate issue (https://github.com/bio-tools/biotoolsRegistry/issues/356).  Future checking will be done via biotoolsLint (https://github.com/bio-tools/biotoolsLint/issues/9)

**Closed** 2018-09-05 10:08 UTC
Labels: GUI, bug, content, critical priority
