### ISSUE TITLE
CBS tools : various issues

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#30] opened 2016-02-19 22:53 UTC
Some of this may have been fixed (the issues is to check / fix as necessary)
1. ProP has wrong data format : GIF should be only one of the formats, we should amend it by adding 'textual format' (or child of)
2. SIgnalP has wrong data format :  binary format, should be textual 
3. Empty documentation on some tools
4. Wrong licenses (is "CBS License" needed, i.e. special license?)

**Comment by joncison** [comment] 2017-11-22 21:12
@hansioan : please reassign to one of your guys so that this gets closed

**Comment by hansioan** [comment] 2018-01-11 12:54
In the case of ProP I'm not sure exactly what the issue is, the format is a combination of text and image. 
http://www.cbs.dtu.dk/services/ProP/output.php
Unless we have multiple data as formats we can only create multiple functions with the same input and operation, but different data for output, the way it is now is the only short and kinda correct way.

SignalP looks fine to me.
The documentation will be handled when we move on with getting all tools to a detailed info level.
CBS license replaced by Other.

@joncison 
I think we can close this.

**Closed** 2018-01-11 13:08 UTC
Labels: bug, content, high priority
