### ISSUE TITLE
bio.tools search (collection name)

### ISSUE THREAD

**Issue by Ahto123** [bio-tools/biotoolsRegistry#318] opened 2018-02-13 11:19 UTC
bio.tools search couldn't retrieve tools that are related to searched tool by collection name (i.e. when the searched tool name is part of the collection name). To illustrate this, let's take a tool called g:Profiler, when we search "g:Profiler" then we cannot see gCocoa or any other tool that have collection name "g:Profiler toolkit". But if we search "g:Profiler toolkit" then we find all those tools. In my opinion it would be better if search doesn't require entire collection name and just part of it would be sufficient. Considering that this issue could affect several tools then maybe it is worth updating the search system?

**Comment by joncison** [comment] 2018-02-14 18:59
Thanks for this report.  You can get the search result by faceting over "Collection":
![capture](https://user-images.githubusercontent.com/1506863/36222377-006b0ab2-11b9-11e8-9c37-78a1464a3bea.PNG)

With that said, we'll consider this more closely in the next iteration of the search behaviour (in all likelihood, after the Summer) cc @piotrgithub1 FHI

**Comment by joncison** [comment] 2018-09-07 12:39
I think the issue is more that we get different results, depending on whether you quote (or not) the search term.

Quoted ("g:profiler"):
https://bio.tools/?page=1&q=%22g:profiler%22&sort=score

Unquoted (g:profiler):
https://bio.tools/?page=1&q=g:profiler&sort=score

which give different results (the top one giving what you wanted, @Ahto123 ?) - but this may not be obvious / intuitive to users.

**Comment by joncison** [comment] 2018-09-07 13:02
This (and other such) issues can be dealt with by https://github.com/bio-tools/biotoolsRegistry/issues/361, so closing this issue.

**Closed by joncison** 2018-09-07 13:02 UTC
Labels: search / sort / filter
