### ISSUE TITLE
SWISS-MODEL Workspace not visible

### ISSUE THREAD

**Issue by heinzstockinger** [bio-tools/biotoolsregistry#170] opened 2017-04-21 09:07 UTC
**SWISS-MODEL Workspace** appears in the search/autosuggestion but if one clicks on it, it does not show up. i.e., the entry for this tool cannot be displayed/listed on the portal.

However, **SWISS-MODEL Repository** is accessible.

**Comment by joncison** [comment] 2017-04-21 09:56
yeah .. we're aware of this issue, it's to do with the way that hyphens are handled.  will be fixed ASAP

searches for "swiss model" or swiss model  (unquoted) brings up the tools

**Comment by heinzstockinger** [comment] 2017-04-21 10:58
ok, thanks.

Currently, I see the following URLs work:

https://bio.tools/tool/swissmodel1 (Repository)
https://bio.tools/tool/swissmodel1/version/1  (Repository)
https://bio.tools/tool/swissmodel2/version/1  (Workspace)

**Comment by joncison** [comment] 2017-05-26 11:58
The de.NBI guys have a problem because whereas searches for "de.NBI" and "de.nbi" return results, the same searches without the quotes do not return results.

@ekry : will you pls. comment here, I suspect there may be a simple fix for this (handling of non-alpha chars) ??

**Comment by joncison** [comment] 2017-06-08 10:43
related to (even duplicate of?) https://github.com/bio-tools/biotoolsregistry/issues/151

**Comment by ekry** [comment] 2017-08-02 14:05
This is fixed and deployed to dev.bio.tools:
https://dev.bio.tools/?page=1&q=%27SWISS-MODEL%20Workspace%27&sort=score&ord=desc
Will be moved to production in the next release.

**Closed by ekry** 2017-08-02 14:05 UTC
Labels: bug, critical priority, search / sort / filter
