### ISSUE TITLE
Searchbar has problems with diacritics and the "Everything" label

### ISSUE THREAD

**Issue by quicknaps** [bio-tools/biotoolsRegistry#230] opened 2017-08-17 02:05 UTC
**The first problem - diacritics**
There's an issue with searching for names with diacritics (letters like č, ř, etc.). 
For some letters the searching keeps on loading forever or for some letters the search says that nothing has been found at all. Both of these situations happen even if the name of the person has been suggested to me by the searchbar. 
For now I found out that the search bar keeps loading forever usually when a name contains ř. When a name contains ž the search usually results in nothing having been found. When a name contains both of these letters it appears that ř takes priority and the search keeps loading forever again.
Examples: 
Searching for Jiří Černý ends up in an infinitely long loading screen. (biotool DNATCO)
Searching for Marie Doležalová ends results in nothing. (biotool IoM - Interpreter of Mass)

**The second problem - ?upper/lowercase letters?**
There's an issue with searching for IoM - Interpreter of Mass with the label "everything". The name of the tool is suggested and that's fine but clicking on the suggested name by the searchbar doesn't find the tool. I had to search for "interpreter" to find this tool. However, once I switch over to the "name" label and search for IoM - Interpreter of Mass then it finds the tool just fine.

**Comment by joncison** [comment] 2017-11-22 19:51
**update**

The second problem is now fixed.   

@ekry - might there be a simple solution to the first problem, or does this need more digging?

**Comment by krab1k** [comment] 2018-02-27 10:39
The first problem is IMHO a serious issue that should be fixed.

I tried that myself: If I type 'raček', the suggestions correctly shows 'tomáš raček' (although without capital letters), hitting Enter or selecting the suggestion results in infinite loading animation. Trying exact match, i.e., 'Tomáš Raček' doesn't work either.

My name is listed in Credits of NEEMP (https://bio.tools/neemp).

**Comment by joncison** [comment] 2018-02-27 13:26
reassigning to @piotrgithub1

**Comment by joncison** [comment] 2018-09-05 09:38
This provides part of the answer:
https://stackoverflow.com/questions/1008287/illegal-mix-of-collations-mysql-error

**Comment by hansioan** [comment] 2018-09-05 09:43
The first issue is that the error comes from logging the query, which most likely means that the query log table has a bad collation and needs to be changed.
Error is:
`(1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")`
at the call
`searchLogger.commit()`
in the file
`/elixir/application/backend/elixir/view/resource.py` line 31

If no logging is done, the error is gone, but the search doesn't perform as expected, although it works for the quoted search of jiří černý.

**Comment by joncison** [comment] 2018-12-12 19:21
@quicknaps @krab1k I think both issues are now fixed - please confirm !

**Comment by krab1k** [comment] 2018-12-13 13:32
Great, it's not stuck anymore!

Just a note: If I type "Raček" and hit enter, I got "Everything: Raček" in the search bar and no results. If I type "Raček" and select "Tomáš Raček" as a suggestion, then it works fine.

Is it an intended behaviour?

**Comment by joncison** [comment] 2018-12-13 14:40
Not really intended .... although if you quote Raček  *i.e.* "Raček" and press enter, it works OK.  So this is still sub-optimal..   We need to rework a bit more the handling by elastic of special characters ...

**Comment by hansioan** [comment] 2018-12-14 09:54
The solution that I think would work best that we ASCII fold the special letters
e.g. no difference in search logic between `Raček` and `Racek`

**Closed** 2024-09-11 11:18 UTC
Labels: search / sort / filter, high priority, partially done
