### ISSUE TITLE
HELP: rare disease domain is down

### ISSUE THREAD

**Issue by lmatalonga** [bio-tools/biotoolsRegistry#362] opened 2018-10-04 13:00 UTC
Hi, 

We had settle up our domain some weeks ago (rare diseases) but it doesn't seems to work now; indeed we had more than 100 resources and now none of them are listed and I can't edit the domain either. Can you check what happened? and why all those resources have disappeared? 

Thanks, 
Leslie

**Comment by joncison** [comment] 2018-10-04 13:34
Just to confirm Leslie, am I right that you worked in https://bio.tools (everything is preserved) and not https://dev.bio.tools (where nothing is preserved) ?

Could you please mail registry-support@elixir-dk.org, including the exact subdomain name and credentials (bio.tools username) of who created it. 

Thanks!  @hansioan can you please pick up on this ASAP?

**Comment by joncison** [comment] 2018-10-04 13:44
@lmatalonga I think the whole site is down!

@piotrgithub1 @hansioan  - please take a look

**Comment by lmatalonga** [comment] 2018-10-04 13:44
Hi John, I confirm I have always worked in https://bio.tools . Indeed we have 2 other subdomains: developed_RD-Connect  and RD-Connect › which work and still active. I will forward this issue to 
mailto:registry-support@elixir-dk.org including the information you mention. 
Thank you very much for your prompt response

**Comment by hansioan** [comment] 2018-10-04 14:03
Hi @lmatalonga 

The domains you own are:

https://bio.tools/?domain=rare-diseases
https://bio.tools/?domain=rd-connect
https://bio.tools/?domain=developed_RD-Connect

and indeed the `rare-diseases` domain has no resources in it. 
I cannot say why, except perhaps there was an error on our server that lost the resources. Can you see and edit the `rare-diseases` domain now? I know the domain doesn't contain any resources, but perhaps you can add them back. I apologize for this problem... it was most likely a server error.

Hans

**Comment by joncison** [comment] 2018-10-04 14:13
I second that  @hansioan @piotrgithub1 - can the list not be traced / recovered from the database?  Definitely, we need to explore this more, so we know for sure a) the cause of the problem (if indeed a server error) and b) how it can be prevented in future.

I notice that https://bio.tools/?page=1&collectionID=%27Rare%20Disease%27&sort=score  returns 99 tools - so most of the subdomain contents can easily be rebuilt, if needed.   But better if we can retrieve this.

**Comment by lmatalonga** [comment] 2018-10-04 14:17
Thanks Jon, 
Yes, for now we can retrieve most of the tools from the collection but if possible it would be great if you could try to recover the whole dataset from the database. I think that for the next tools I will try to feed both: the collection and the domain so that if this happens again we can retrieve "easily" most of the tools. 
Thanks all for your help

**Comment by joncison** [comment] 2018-10-04 14:19
yeah .. I was going to recommend that (use the "collection" field to tag all relevant tools).  In any case, Hans and/or PJ will look into the cause of the problem, and get back soon.

**Comment by hansioan** [comment] 2018-10-04 14:51
@lmatalonga 
We will find out if we can recover the resources and I will post back here as soon as we do.

**Comment by piotrgithub1** [comment] 2018-10-04 16:13
Hi,

I am still trying to recover the data, will let you know what's the result once I have some answers.

Best regards,
Piotr

**Comment by lmatalonga** [comment] 2018-10-05 14:38
HI, 
I have added the rare disease collection to the domain so that we do not leave the domain empty, but please if you can recover the whole dataset feel free to replace it. 
Thanks!
Leslie

**Comment by joncison** [comment] 2018-10-12 09:54
Hi @lmatalonga, it turns out we had two problems, one concerning hardware (which we're still resolving), and another concerning our backup process (which has since been fixed).  Right now, the problem could in principle (unlikely) re-occur, but we'd be able to restore the data.  

I leave this issue open until all problems have been sorted.

**Comment by lmatalonga** [comment] 2018-11-29 15:19
Hi @joncison<https://github.com/joncison>,

Happy to hear that the problem has been fixed. Pages look fine. As we just moved from the registries to the subdomains; we haven’t loose information (only a few tools that I have added back).

Thanks for the support!

Best,

Leslie

**Comment by hmenager** [comment] 2018-12-02 15:39
fix confirmed

**Comment by joncison** [comment] 2018-12-14 13:53
cc @lmatalonga

**Closed by joncison** 2018-12-14 13:53 UTC
Labels: bug, content, critical priority, fix verified

**Comment by joncison** [comment] 2019-02-16 14:39
@lmatalonga just to let you know that https://bio.tools/electronic_pharmacogenomics_assistant_epga (which is tagged as in the "Developed_RD-Connect" and "Rare Disease" collections) will soon be deleted.  It duplicates https://bio.tools/epga/.

**Comment by lmatalonga** [comment] 2019-02-18 07:59
Thanks @joncison . I've tried to update the subdomain but it gives me an error: "Domain could not be created. Could not locate resource with id Knowledge.bio_LWAS ." 

Also I've seen we have 101 tools listed in the rare-diseases subdomain but only 95 are displayed in https://bio.tools/?domain=rare-diseases . Could this be because other duplicates have been resolved and maybe the once we listed removed?

**Comment by joncison** [comment] 2019-02-18 13:03
Yup - we're in the middle of a big clean-up.  I tried to preserve all the collection annotations where merges or deletes were necessary.  The process is still ongoing and the database may not to be up to date ... so let's take a look in a week or so ...

**Comment by lmatalonga** [comment] 2019-04-03 07:12
Hi @joncison 

For some reason I cannot add resources to the rare-diseases subdomain nor update it. The error is "Domain could not be created. Could not locate resource with id Knowledge.bio_LWAS ."

Thanks for your help. 
Leslie
