### ISSUE TITLE
Filtering on toolType doesn't work

### ISSUE THREAD

**Issue by dansondergaard** [bio-tools/biotoolsregistry#232] opened 2017-09-01 11:30 UTC
The following doesn't work (I tried both with curl and Python's `requests`):

```
$ curl -X GET 'https://bio.tools/api/tool/?toolType=Command-line+tool'
{"count":0,"previous":null,"list":[],"next":null}
```
The [example](http://biotools.readthedocs.io/en/latest/api_reference.html#example) in the docs works fine.

Am I doing something wrong?

**Comment by magnuspalmblad** [comment] 2017-09-01 13:54
I too get 0 counts, also for other toolTypes, so I think the problem is on the server side (assuming it is supposed to allow you to execute this search).

**Comment by ekry** [comment] 2017-09-04 13:03
This is fixed now - results should be returned as expected.

**Closed by ekry** 2017-09-04 13:03 UTC
Labels: API, bug, search / sort / filter
